# Generated by Django 5.1 on 2024-09-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_patientprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
