# Generated by Django 5.1 on 2024-09-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_patientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
