# Generated by Django 5.1 on 2024-09-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_patientprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married')], default='S', max_length=10),
        ),
    ]
