# Generated by Django 5.1 on 2024-09-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_blogpost_alter_patientprofile_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
