# Generated by Django 5.1 on 2024-09-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_department_doctor_clinichours_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinichours',
            name='sunday_closed',
        ),
        migrations.AddField(
            model_name='clinichours',
            name='sunday_end',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='clinichours',
            name='sunday_start',
            field=models.TimeField(default=None, null=True),
        ),
    ]
