# Generated by Django 5.1 on 2024-09-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_clinichours_sunday_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinichours',
            name='saturday_end',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clinichours',
            name='saturday_start',
            field=models.TimeField(default=None, null=True),
        ),
    ]
