# Generated by Django 5.1 on 2024-09-23 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.patientprofile'),
        ),
    ]
